### ISSUE TITLE
Timezone

### ISSUE THREAD

**Issue by StephanMa** [NovaFox161/DisCal-Discord-Bot#3]
When adding an Event to a calendar, the timezone and starting time are converted in another timezone.
So it is not usable for european Users because it lists the starting time in US(?)-Time...

**Comment by NovaFox161** [comment]
Will look into. Thought this was patched a while ago, but it may have broken again.

**Comment by NovaFox161** [comment]
@StephanMa 
Would you mind specifying the date/time format you would like to see? As I am not located in europe

**Comment by StephanMa** [comment]
The most common format in Europe should be dd.mm.yyyy Hh:mm:ss 
This would be very nice. Maybe I can help you realizing some features. I am an experienced programmer as well :)

**Comment by NovaFox161** [comment]
Alrighty, I will work on adding this format.

And I would love the help! The more help the better really.

**Comment by StephanMa** [comment]
Alright then ... maybe you can open some issues with enhancement ideas and let's see what we are able to realize :)

**Comment by NovaFox161** [comment]
Quick idea @StephanMa 
Since the time/date formats vary depending on region, and could get confusing, what if the ability to set the format was an option?
By default, it was set to the current format, but you could edit it so that it could be in the format you specified above or in other formats depending on the region and user choice.

Creating events will still be in the current formats, but the displays will be changed depending on this format.

Easy to implement, just wondering if that could be a solution

**Comment by NovaFox161** [comment]
Timezone bug fixed in recent commit: https://github.com/NovaFox161/DisCal-Discord-Bot/commit/c934d128d864aaf84cde9212a4a1aabd1e062206

Please open another (enhancement) ticket if the aforementioned settings for custom date/time formats is still an interest. 

Thank you for reporting the bug!
